# Generated by Django 3.1.6 on 2022-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20220130_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primtodo',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
